_wandb:
    value:
        cli_version: 0.26.0
        e:
            grwhratxh1bdzeaxr6t31inltq3987ih:
                args:
                    - --epochs
                    - "1"
                    - --batch_size
                    - "256"
                    - --wandb_mode
                    - online
                codePath: train.py
                codePathLocal: train.py
                cpu_count: 12
                cpu_count_logical: 24
                cudaVersion: "13.2"
                disk:
                    /:
                        total: "429496725504"
                        used: "218827571200"
                email: wang2514289689@gmail.com
                executable: D:\tools\anaconda3\python.exe
                gpu: NVIDIA GeForce RTX 5090 Laptop GPU
                gpu_count: 1
                gpu_nvidia:
                    - architecture: Blackwell
                      cudaCores: 10496
                      memoryTotal: "25651314688"
                      name: NVIDIA GeForce RTX 5090 Laptop GPU
                      uuid: GPU-bfdacefd-7f3a-ee61-4081-5dafe6c8c9f8
                host: Razer16-WZP
                memory:
                    total: "33412730880"
                os: Windows-11-10.0.26200-SP0
                program: D:\study\02硕士\课程\06深度学习\HUST_DL_Course\01Numpy神经网络\train.py
                python: CPython 3.13.5
                root: ./runs/mnist_manual_numpy\relu\He\dropout_0p0\20260414_215656_592231
                startedAt: "2026-04-14T13:57:01.833998Z"
                writerId: grwhratxh1bdzeaxr6t31inltq3987ih
        m: []
        python_version: 3.13.5
        t:
            "1":
                - 1
                - 5
                - 53
            "2":
                - 1
                - 5
                - 53
            "3":
                - 2
                - 13
                - 16
                - 61
                - 62
            "4": 3.13.5
            "5": 0.26.0
            "8":
                - 3
            "10":
                - 20
            "12": 0.26.0
            "13": windows-amd64
activation:
    value: relu
batch_size:
    value: 256
data_home:
    value: ./scikit_data
dropout_rate:
    value: 0
epochs:
    value: 1
hidden_num1:
    value: 256
hidden_num2:
    value: 128
l2_lambda:
    value: 0
log_dir:
    value: ./runs/mnist_manual_numpy\relu\He\dropout_0p0\20260414_215656_592231
lr:
    value: 0.02
method:
    value: He
run_suffix:
    value: relu\He\dropout_0p0\20260414_215656_592231
save_dir:
    value: ./outputs\relu\He\dropout_0p0\20260414_215656_592231
seed:
    value: 20260318
wandb_mode:
    value: online
