_wandb:
    value:
        cli_version: 0.26.0
        e:
            cwsmhtuehm5em3nvnlhgmovl8dxnfebz:
                args:
                    - --wandb_mode
                    - online
                    - --activation=relu
                    - --batch_size=64
                    - --dropout_rate=0
                    - --epochs=10
                    - --hidden_num1=256
                    - --hidden_num2=128
                    - --l2_lambda=0.001
                    - --lr=0.043553196347783714
                    - --method=He
                    - --seed=20260318
                codePath: train.py
                codePathLocal: train.py
                cpu_count: 12
                cpu_count_logical: 24
                cudaVersion: "13.2"
                disk:
                    /:
                        total: "429496725504"
                        used: "218830286848"
                email: wang2514289689@gmail.com
                executable: D:\tools\anaconda3\python.exe
                gpu: NVIDIA GeForce RTX 5090 Laptop GPU
                gpu_count: 1
                gpu_nvidia:
                    - architecture: Blackwell
                      cudaCores: 10496
                      memoryTotal: "25651314688"
                      name: NVIDIA GeForce RTX 5090 Laptop GPU
                      uuid: GPU-bfdacefd-7f3a-ee61-4081-5dafe6c8c9f8
                host: Razer16-WZP
                memory:
                    total: "33412730880"
                os: Windows-11-10.0.26200-SP0
                program: D:\study\02硕士\课程\06深度学习\HUST_DL_Course\01Numpy神经网络\train.py
                python: CPython 3.13.5
                root: ./runs/mnist_manual_numpy\relu\He\dropout_0p0\20260414_220042_956915
                startedAt: "2026-04-14T14:00:48.232563Z"
                writerId: cwsmhtuehm5em3nvnlhgmovl8dxnfebz
        m: []
        python_version: 3.13.5
        t:
            "1":
                - 1
                - 5
                - 53
            "2":
                - 1
                - 5
                - 53
            "3":
                - 2
                - 13
                - 14
                - 16
                - 61
                - 62
            "4": 3.13.5
            "5": 0.26.0
            "8":
                - 3
            "12": 0.26.0
            "13": windows-amd64
activation:
    value: relu
batch_size:
    value: 64
data_home:
    value: ./scikit_data
dropout_rate:
    value: 0
epochs:
    value: 10
hidden_num1:
    value: 256
hidden_num2:
    value: 128
l2_lambda:
    value: 0.001
log_dir:
    value: ./runs/mnist_manual_numpy\relu\He\dropout_0p0\20260414_220042_956915
lr:
    value: 0.043553196347783714
method:
    value: He
run_suffix:
    value: relu\He\dropout_0p0\20260414_220042_956915
save_dir:
    value: ./outputs\relu\He\dropout_0p0\20260414_220042_956915
seed:
    value: 20260318
wandb_mode:
    value: online
